import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export type Tables = {
  user_profile: {
    id: string;
    username: string | null;
    display_name: string | null;
    avatar_url: string | null;
    skill_rating: number;
    preferred_doubles: number[];
    theme: 'dark' | 'light' | 'system';
    locale: string;
    auto_update: boolean;
    email_notifications: boolean;
    push_notifications: boolean;
    is_admin: boolean;
    total_games_played: number;
    total_wins: number;
    total_checkouts: number;
    highest_checkout: number;
    average_score: number;
    best_average: number;
    current_streak: number;
    longest_streak: number;
    last_active_at: string;
    created_at: string;
    updated_at: string;
  };
  drills: {
    id: string;
    category: string;
    name_key: string;
    desc_key: string;
    config: Record<string, unknown>;
    difficulty: number;
    estimated_minutes: number;
    is_active: boolean;
    sort_order: number;
    created_at: string;
    updated_at: string;
  };
  programs: {
    id: string;
    name_key: string;
    desc_key: string;
    config: Record<string, unknown>;
    duration_days: number;
    daily_minutes: number;
    difficulty: number;
    target_skill: string | null;
    is_active: boolean;
    sort_order: number;
    created_at: string;
    updated_at: string;
  };
  challenges: {
    id: string;
    name_key: string;
    desc_key: string;
    rule: Record<string, unknown>;
    reward: Record<string, unknown>;
    is_active: boolean;
    start_date: string | null;
    end_date: string | null;
    created_at: string;
    updated_at: string;
  };
  game_rooms: {
    id: string;
    game_type: string;
    starting_score: number;
    legs_to_win: number;
    sets_to_win: number;
    double_in: boolean;
    double_out: boolean;
    mode: 'bot' | 'pvp' | 'local';
    bot_difficulty: string | null;
    bot_style: string | null;
    bot_params: Record<string, unknown> | null;
    status: string;
    winner_id: string | null;
    tournament_match_id: string | null;
    created_by: string;
    started_at: string | null;
    completed_at: string | null;
    created_at: string;
  };
  clubs: {
    id: string;
    name: string;
    description: string | null;
    avatar_url: string | null;
    banner_url: string | null;
    join_policy: 'open' | 'request' | 'invite';
    min_skill_rating: number | null;
    max_members: number;
    is_active: boolean;
    total_members: number;
    total_games: number;
    total_wins: number;
    average_skill: number;
    created_by: string;
    created_at: string;
    updated_at: string;
  };
  tournaments: {
    id: string;
    name: string;
    description: string | null;
    game_type: string;
    starting_score: number;
    legs_per_match: number;
    sets_per_match: number;
    format: string;
    min_players: number;
    max_players: number;
    min_skill_rating: number | null;
    max_skill_rating: number | null;
    entry_fee_tokens: number;
    prize_pool_tokens: number;
    status: string;
    registration_starts_at: string | null;
    registration_ends_at: string | null;
    starts_at: string | null;
    completed_at: string | null;
    winner_id: string | null;
    created_by: string;
    club_id: string | null;
    created_at: string;
    updated_at: string;
  };
  notification_receipts: {
    id: string;
    user_id: string;
    notification_id: string | null;
    title: string;
    body: string;
    category: string;
    image_url: string | null;
    action_url: string | null;
    is_read: boolean;
    read_at: string | null;
    created_at: string;
  };
  app_config: {
    id: string;
    key: string;
    value_json: unknown;
    type: string;
    description_key: string | null;
    updated_by_user_id: string | null;
    updated_at: string;
    created_at: string;
  };
};
